In [1]:
!pip install -q google-generativeai PyPDF2 gradio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 4.6 MB/s eta 0:00:00

In [2]:
import google.generativeai as genai
import os
import pandas as pd
import numpy as np
from PyPDF2 import PdfReader

/usr/local/lib/python3.13/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)

In [3]:
from google.colab import userdata
api_key = userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=api_key)
print("google.generativeai library imported and configured.")

google.generativeai library imported and configured.

In [4]:
import time

def call_with_retry(fn, *args, retries=2, delay=3, **kwargs):
    """Call fn(*args, **kwargs); retry on transient Gemini errors (503/429/timeout).
    Re-raises the last error if all attempts fail, so callers still see a real failure
    instead of this silently returning nothing."""
    last_err = None
    for attempt in range(retries + 1):
        try:
            return fn(*args, **kwargs)
        except Exception as e:
            last_err = e
            transient = any(s in str(e) for s in ("503", "429", "Timeout", "Deadline", "overloaded", "UNAVAILABLE"))
            if not transient or attempt == retries:
                raise
            print(f"Transient error ({type(e).__name__}), retrying in {delay}s... (attempt {attempt + 1}/{retries})")
            time.sleep(delay)
    raise last_err

In [ ]:
# Single place to change the generation model - swap here if the current one is hitting rate limits/overload
# (e.g. "gemini-3.5-flash" if a heavier model is needed).
MODEL_NAME = "gemini-3.5-flash-lite"

## Етап 1: зчитування даних

In [5]:
df = pd.DataFrame(columns=['Title','Text'])
df

Empty DataFrame
Columns: [Title, Text]
Index: []

In [6]:
# Brightdesk demo docs, loaded inline (no PDF upload needed for this demo run).
brightdesk_docs = {
    'Onboarding Guide': "# Brightdesk — New Hire Onboarding Guide\n\n## Before Your First Day\n- IT will email your account credentials 3 business days before your start date. If you haven't received them by then, contact it-support@brightdesk.example.\n- Bring a government-issued ID for identity verification on day one.\n- Your manager will send a calendar invite for a 30-minute welcome call on your first morning.\n\n## First Week Checklist\n1. Complete the HR intake form (personal details, emergency contact, tax forms).\n2. Set up your company laptop and enroll in two-factor authentication.\n3. Meet with your onboarding buddy (assigned by your manager) for a team walkthrough.\n4. Review the Employee Handbook and acknowledge receipt in the HR portal.\n5. Schedule 1:1s with your direct manager and skip-level manager within the first two weeks.\n\n## Probation Period\nAll new hires have a 90-day probation period. Formal check-ins happen at day 30, day 60, and day 90. Full benefits eligibility (health insurance, 401k/pension matching) begins on day 1, but probation performance is reviewed before the role is confirmed as permanent.\n\n## Equipment\nStandard equipment (laptop, monitor, headset) is provided by IT. Requests for additional equipment go through the #it-requests channel and are typically fulfilled within 5 business days.\n",
    'Leave and Vacation Policy': "# Brightdesk — Leave & Vacation Policy\n\n## Paid Time Off (PTO)\nFull-time employees accrue 24 calendar days of paid annual leave per year (the statutory minimum under Ukrainian labor law), credited at 2 days per month worked. Unused PTO up to 5 days may be carried over into the next calendar year; anything beyond that is forfeited unless local law requires otherwise.\n\n## Requesting Leave\nSubmit leave requests through the HR portal at least 5 business days in advance for planned leave. Requests are approved by your direct manager. Leave taken without prior approval (except sick leave) may be recorded as unpaid.\n\n## Sick Leave\nEmployees receive 10 paid sick days per year, separate from PTO. A doctor's note is required for absences longer than 3 consecutive days. Sick leave does not need to be scheduled in advance.\n\n## Parental Leave\n- Primary caregiver: 16 weeks paid leave.\n- Secondary caregiver: 6 weeks paid leave.\nParental leave can be taken within 12 months of the birth or adoption date and does not need to be used consecutively.\n\n## Public Holidays\nBrightdesk observes 11 public holidays per year, published annually in the HR portal calendar. Employees working in a different country follow their local public holiday calendar.\n\n## Bereavement Leave\nUp to 5 paid days for the loss of an immediate family member, and 2 paid days for extended family, at manager's discretion for edge cases.\n",
    'Health Insurance and Benefits': '# Brightdesk — Health Insurance & Benefits\n\n## Medical Insurance\nBrightdesk covers 100% of the employee\'s medical insurance premium and 50% of dependents\' premiums under the standard plan. Coverage begins on the first day of employment, with no waiting period. Enrollment or plan changes are handled through the benefits portal within 30 days of a qualifying life event (marriage, birth, relocation).\n\n## Dental & Vision\nOptional dental and vision add-ons are available at the employee\'s cost, with a 20% company subsidy. These can be added during open enrollment (every November) or within 30 days of hire.\n\n## Retirement / Pension Matching\nBrightdesk matches retirement contributions up to 4% of base salary, vested immediately (no vesting schedule). Contributions can be adjusted at any time through the payroll portal.\n\n## Wellness Stipend\nEmployees receive a $50/month wellness stipend reimbursable for gym memberships, fitness classes, or mental health app subscriptions. Submit receipts through the expense portal under category "Wellness."\n\n## Learning & Development Budget\nEach employee has an annual $1,000 learning budget for courses, certifications, or conference tickets, subject to manager approval. Unused budget does not roll over to the next year.\n',
    'Remote and Hybrid Work Policy': "# Brightdesk — Remote & Hybrid Work Policy\n\n## Work Location\nEmployees on hybrid contracts are expected in the office 2 days per week (Tuesday and Thursday, unless otherwise agreed with a manager). Fully remote roles are defined at the offer stage and do not have an office attendance requirement.\n\n## Working Hours\nCore collaboration hours are 11:00–16:00 in the employee's local timezone. Outside core hours, employees may structure their schedule flexibly as long as deliverables and meeting commitments are met.\n\n## Equipment for Remote Work\nRemote employees receive a one-time $300 home office stipend for desk/chair setup, plus standard IT-issued equipment (laptop, monitor). Requests go through the #it-requests channel.\n\n## Working From Abroad\nEmployees may work from another country for up to 30 consecutive days per year without prior HR approval, provided it does not affect tax residency. Longer periods require sign-off from HR and Legal due to tax and compliance implications.\n\n## Internet & Connectivity\nA $40/month home internet stipend is available for fully remote employees, reimbursed through the expense portal.\n",
}

for title, text in brightdesk_docs.items():
    text = text.replace('\n', ' ')
    new_row = pd.DataFrame({'Title': [title], 'Text': [text]})
    df = pd.concat([df, new_row], ignore_index=True)

In [7]:
df

,Title,Text
0,Onboarding Guide,# Brightdesk — New Hire Onboarding Guide ## B...
1,Leave and Vacation Policy,# Brightdesk — Leave & Vacation Policy ## Pai...
2,Health Insurance and Benefits,# Brightdesk — Health Insurance & Benefits ##...
3,Remote and Hybrid Work Policy,# Brightdesk — Remote & Hybrid Work Policy ##...

In [8]:
print(df['Text'].iloc[1])

# Brightdesk — Leave & Vacation Policy  ## Paid Time Off (PTO) Full-time employees accrue 24 calendar days of paid annual leave per year (the statutory minimum under Ukrainian labor law), credited at 2 days per month worked. Unused PTO up to 5 days may be carried over into the next calendar year; anything beyond that is forfeited unless local law requires otherwise.  ## Requesting Leave Submit leave requests through the HR portal at least 5 business days in advance for planned leave. Requests are approved by your direct manager. Leave taken without prior approval (except sick leave) may be recorded as unpaid.  ## Sick Leave Employees receive 10 paid sick days per year, separate from PTO. A doctor's note is required for absences longer than 3 consecutive days. Sick leave does not need to be scheduled in advance.  ## Parental Leave - Primary caregiver: 16 weeks paid leave. - Secondary caregiver: 6 weeks paid leave. Parental leave can be taken within 12 months of the birth or adoption date and does not need to be used consecutively.  ## Public Holidays Brightdesk observes 11 public holidays per year, published annually in the HR portal calendar. Employees working in a different country follow their local public holiday calendar.  ## Bereavement Leave Up to 5 paid days for the loss of an immediate family member, and 2 paid days for extended family, at manager's discretion for edge cases.

## Етап 2: Векторизація

In [9]:
texts = df['Text']
task_type = 'RETRIEVAL_DOCUMENT'
result = genai.embed_content(model="gemini-embedding-001", content=texts)
print(result)

{'embedding': [[-0.006957309, 0.015669828, -0.002305022, -0.05786128, 0.023529692, 0.021365006, -0.0048412452, -0.010775757, -0.037184883, -0.006749296, -0.05041439, -0.010716306, 0.00018510461, -0.007115277, 0.11918452, -0.016847137, 0.014053316, 0.0037684322, 0.0012318222, -0.019463938, -0.0091748675, 0.014780136, 0.004766676, -0.0023347707, -0.022118734, -0.030557282, 0.035106838, 0.030003343, 0.042310067, 0.0007536542, 0.0010637754, 0.02587698, 0.0078955535, 0.0282977, -0.0031126952, 0.023079716, -0.010645984, 0.0008762546, -0.013065552, 0.016391497, 0.008287095, 0.014236358, -0.017534593, -0.020157427, -0.008688459, -0.009051389, -0.006668721, 0.0042255097, -0.0076902406, 0.021984987, -0.01772308, 0.01311187, -0.007437147, -0.19306765, -0.0048237303, -0.027916854, 0.006469652, -0.0028410193, 0.01916372, -0.028317709, 0.0011445108, 0.027103094, -0.046611074, -0.028726097, -0.009938895, -0.026199052, 0.0010534151, -0.005843079, 0.02205556, -0.019225411, 0.004598728, 0.0069517074, -0.0026115673, -0.03148483, -0.0052708876, -0.029789438, -0.0044351704, -0.021154126, 0.012814803, -0.0030102835, -0.021098362, -0.019691022, 0.006589136, -0.018243307, 0.012318603, -0.015774535, 0.0074369637, 0.021156948, -0.019812785, 0.023866039, 0.005660511, 0.034419365, -0.0072480356, -0.025951471, 0.0058726543, -0.00260082, 0.009396817, -0.008850699, -0.0015216726, -0.002283233, -0.014574505, -0.029328248, 0.007475457, -0.0060906666, 0.020453634, 0.0003087988, 0.015386449, -0.012823073, 0.018502323, 0.0016649406, 0.026398726, 0.011656987, -0.0019358371, 0.0024599936, 0.0144286845, -0.14411634, 0.008377012, 0.013190595, 0.0018847685, -0.01302812, -0.023854386, -0.032347646, -0.00107325, 0.003671256, 0.0054504075, -0.012583231, 0.014545558, -0.010788116, -0.0029257466, 0.021056337, -0.033926614, -0.035342798, 0.007873551, -0.013206373, 0.026540905, 0.012513233, -0.016148603, 0.0010202997, -0.010420467, -0.040178932, 0.016246047, 0.0019929528, -0.010983823, 0.012223829, -0.02620297, -0.010236148, -0.022190329, -0.023381555, -0.011321529, -0.029463202, -0.012903906, -0.013764899, -0.0044145063, -0.011079903, 0.0141564235, -0.014330737, 0.0028677438, 0.023255784, -0.02871454, -0.022105947, 0.0041162274, 0.010466678, -0.000112133894, 0.006979115, 0.009751928, -0.00071152765, 0.018760612, 0.012345246, -0.017813923, 0.0073928963, 0.018152546, 0.0064031244, 0.005509517, -0.001335606, -0.011505305, -0.019824637, -0.0036490848, -0.0006174745, 0.019013777, -0.019193154, -0.00090558187, -0.01663853, -0.009790892, 0.013635551, 0.0181677, 0.0029787775, 0.007339864, 0.010203617, 0.017088145, 0.015353683, -0.02050618, 0.013611949, 0.0046169376, -0.008143069, -0.018650427, -0.027794288, -0.01733395, 0.0021845785, -0.009520841, 0.030529331, 0.02044791, 0.012316591, 0.0006312857, -0.006613526, 0.021094635, 0.009558974, -0.017397474, 0.0133248065, 0.0066456255, 0.03162709, 0.004495852, 0.021490376, 0.0070809573, 0.00090470404, 0.011781733, -0.033968277, -0.017516246, -0.009622809, -0.0022691053, 0.0032460298, 0.009731705, 0.0026974971, 0.008519563, 0.030932203, -0.0013929037, -0.006570089, 0.02161323, -0.033569574, 0.014153057, -0.015558878, -0.00020521255, 0.007661265, -0.00279087, 0.016522836, 0.027558742, -0.023080433, 0.0029092375, 0.015251797, -0.0009400235, 0.027693642, 0.006724716, -0.032711055, -0.00016345487, 0.0035831358, 0.012997335, -0.0046951165, 0.0075284163, -0.015683673, -0.0029373353, 0.01630179, -0.020581407, 0.0013299892, -0.003841935, -0.01769441, -0.030536652, 0.031101616, 0.0008907687, -0.015118233, 0.009263769, -0.019895134, -0.021494253, 0.009243289, -0.0076835025, -0.011897752, -0.0048949653, 0.0074055013, 0.015766434, 0.013714811, -0.0110406885, -0.0054062963, 0.0028140678, -0.00487227, -0.017888013, 0.0016033452, 0.015256297, 0.000409635, -0.05827096, 0.025613658, 0.0091681825, -0.01937675, -0.030638877, 0.003576104, 0.028409231, -0.0075114653, 0.0023306145, 0.03187954, -0.0035543516, -0.006887985, 0.025248004, -0.011044169, 0.0013929872, -0.015678875, -0.008823701, 0.0026428027, 0.0043640067, -0.0068541574, 0.000108455475, -0.0025795538, 0.008587824, -0.024126664, 0.0076350463, -0.02640558, 0.012395046, 0.04841188, 0.0057653924, -0.00662543, 0.007996116, 0.037285924, -0.009713399, -0.0023247777, 0.010739214, 0.030287469, 0.017888304, -0.00014110988, 0.0036735993, 0.011221185, 0.04596454, 0.0029750492, -0.0063028443, -0.006647099, -0.0014908027, 0.015920667, -0.028078724, 0.023184774, -0.011430571, 0.018228771, -0.010094402, 0.017828176, -0.013510195, 0.00043033497, 0.011357273, 0.011346833, -0.016109336, -0.006331869, 0.026737766, 0.018367754, 0.0016630401, -0.004468436, 0.004337949, 0.02103938, 0.020943947, 0.015236904, -0.031120546, 0.014274784, -0.03757023, 0.008687874, 0.019478956, -0.009532437, 0.010738215, 0.007057664, -0.01623906, -0.009992156, 0.0021420682, -0.00078018766, -0.0213094, 0.00048825078, 0.003038082, -0.009535905, -0.0010332714, 0.026909126, 0.0090365345, -0.0028713525, -0.020069394, 0.009168701, 0.006166015, -0.014362823, 0.002947943, 0.008746861, -0.008117606, -0.0038933868, -0.022357078, 0.0055316295, 0.012608725, -0.019616658, -0.029031893, 0.0019272306, -0.0027843835, 0.014144194, 0.012072879, 0.007380538, -0.0244136, 0.008989904, 0.006218713, -0.00061965716, 0.0088014975, 0.003503869, 0.019393235, 0.006576538, 0.010337435, 0.01413529, -0.004666979, 0.014876828, 0.0120347915, -0.0072819646, -0.0061727664, -0.014646434, -0.0013495507, -0.0053897155, -0.011082851, 0.014597513, -0.015419381, 0.011139686, -0.032421857, 0.011327202, -0.011090442, 0.0077604474, 0.021720381, -0.01978818, 0.0070183896, -0.0006406451, 0.013028441, 0.01073349, -0.0013911017, -0.015720885, 0.010608837, -0.01141159, -0.010460157, 0.003649222, 0.01845978, -0.014758722, 0.020884693, -0.0076889526, -0.011219743, 0.0016219029, 0.016802914, 0.013149691, -0.016746225, -0.012982723, -0.018292911, 0.0038944902, 0.014947065, -0.0005406652, -0.01797119, -0.026920985, -0.028709097, -0.013983697, -0.019278215, 0.00791074, -0.02837031, 0.0045763636, -0.004020105, 0.017748497, -0.016729258, -0.0051218597, 0.032312192, -0.009404596, 0.018061645, -0.01969009, -0.013479107, -0.02295197, 0.006102712, 0.0075784344, -0.01534882, -0.010011492, 0.012054755, 0.010477768, -0.017026795, -0.010900024, -0.014305251, -0.004126734, 0.00081447186, 0.011834731, 0.013867212, 0.008115558, 0.001018451, -0.0068152235, -0.00061402895, -0.007193424, 0.016048241, 0.021828603, -0.00875956, -0.0016615867, -0.0152747035, -0.03213149, 0.012043393, -0.028146384, -0.0077240192, -0.029450214, 0.021437638, 0.015906373, 0.0082409745, -0.0037599308, 0.0021780846, -0.0012635122, -0.008610907, 0.0043145358, -0.01200724, 0.00751163, -0.0062006037, 0.0025174369, 0.017537294, 0.02212468, -0.015253419, 0.008937966, -0.04649194, 0.014861212, 0.020900141, 0.030753085, 0.022856658, 0.0077218935, -0.014415543, 0.0072064092, -0.014147817, 0.009112485, -0.0009659889, -0.005192122, 0.013186235, -0.0044482583, 0.0038130577, 0.0032619282, 0.00048251107, -0.003249979, -0.024061056, 0.037434157, -0.018431876, 0.0013780429, 0.0032618036, 0.011703706, 0.021091403, -0.023877747, -0.023401175, 0.014872387, -0.014068313, 0.006770194, 0.008052453, 0.013485705, -0.0003951377, -0.005422259, 0.022045504, -0.029803464, -0.01028315, 0.0367672, -0.02710332, -0.027690396, 0.004844998, -0.010683812, -0.009076664, 0.030086676, 0.0017607885, 0.0059857564, -0.03776797, -0.0028822746, -0.011710007, 0.0061040944, -0.021320846, -0.11777184, -0.008099914, 0.016491333, -4.5193206e-05, -0.001130553, -0.009292864, -0.0015350928, 0.024535283, -0.012586336, -0.00468004, 0.012458158, 0.007288378, -0.00055591593, -0.008151375, -0.010474431, -0.023087569, -0.0128946565, 0.001283177, -0.0018810987, -0.023517186, -0.019398764, 0.017950654, 0.011261478, -0.020438543, 0.010990099, -0.012188055, 0.013025339, 0.003183992, -0.0011437347, 0.017643917, -0.014091024, 0.0013353154, 0.0010131837, 0.047339283, -0.0069637783, -0.0038840552, 0.0010821765, -0.030030899, 0.015363363, -0.018199574, 0.004674435, 0.0016789743, -0.003156738, -0.019701408, 0.013089889, 0.01583575, 0.0037070836, -0.02089062, 0.02730666, 0.0046813847, -0.021381725, -0.012013705, -0.02650883, -0.006970858, 0.028286267, 0.00075734104, -0.03375607, 0.033477943, -0.032958522, 0.011002776, -0.03649155, 0.00043788663, -0.0018156633, 0.028502112, 0.003530113, 0.018935088, 0.0021837116, -0.0014462505, -0.015171538, -5.570354e-05, -0.034273416, -0.05368163, 0.0018897044, 0.015493302, -0.028471168, -0.029503101, 0.008460158, 0.054621425, 0.00062822166, -0.006551077, 0.009617354, 0.0026791778, -0.069115154, 0.009591412, -0.010802567, -0.010600622, 0.013948249, 0.005206551, 0.018235076, -0.023864219, -0.020203676, 0.0072875465, 0.003783323, -0.008092805, 0.018910727, -0.011774473, 0.04001247, 0.014837539, -0.011575248, 0.010044691, -0.026091367, -0.018618457, -0.008455403, 0.009378545, -0.0028360656, 0.0007577961, -6.90395e-05, 0.005739788, 0.022605719, -0.0073750955, 0.008133341, -0.031555887, -0.0031582438, -0.16355214, 0.010529357, -0.027211448, 0.031537287, 0.0072207884, 0.015796484, 0.025416654, 0.0050912974, -0.008097813, -0.019020814, 0.017622676, -0.05231363, -0.047150627, -0.0052467547, 0.010050182, 0.08819803, -0.011349501, -0.00932716, -0.01324242, -0.011686042, -0.0066335374, -0.015062125, -0.0073319497, -0.0070075756, -0.011213317, -0.014392903, -0.013686686, 7.829488e-05, 0.0131067205, 0.0112530645, 0.0029807459, -0.01330456, -0.011923888, 0.011842413, -0.013879762, -0.012015627, 0.017920908, -0.009755646, -0.011297928, 0.01021835, 0.023353502, 0.017723445, 0.014491105, -0.018726232, -0.003976626, -5.3549476e-05, 0.0030852463, -0.005279204, 0.012509754, -0.011669444, -0.02992691, -0.050057784, -0.0067745396, 0.0075399294, 0.034603156, -0.0007848108, -0.015554789, 0.004279748, -0.003479841, -0.004537522, 0.009372092, 0.017952833, 0.01749478, 0.03704984, -0.023933817, -0.0011843764, 0.025904458, 0.0122597525, -0.02254661, -0.008271346, 0.022395398, 0.00018988502, 0.009094417, -0.0013342076, -0.008706739, -0.020677213, 0.0065759937, -0.013738922, -0.006125026, -0.012289529, -0.015012152, 0.010692073, 0.029661218, -0.02834397, -0.049146604, 0.010002875, 0.009288483, 0.02703869, 0.0015956092, -0.004894015, 0.009934602, 0.04448145, 0.0008698589, -0.009765205, -0.007260715, -0.011940574, 0.011744918, 0.01863586, -0.020236917, -0.020724298, 0.029906096, -0.012775816, -0.010328664, -0.020885378, -0.034516636, 0.0007573511, 0.02835182, -0.019815212, 0.033684026, 0.007923781, 0.0037525564, -0.009772003, -0.0024253007, 0.0048570475, 0.0010126968, -0.0039377315, 0.0076698987, -0.0038846233, -0.0019183815, -0.0058784913, 0.0038078167, 0.015233998, -0.0062239002, 0.013715375, 0.010206204, -0.0019078121, -0.0021470946, -0.00047623282, 0.0064562913, -0.026592268, 0.007725181, -0.012191913, -0.0006115777, 0.0010003304, 0.00090676546, 0.0039481116, 0.0018484518, -0.00031211803, 0.0008182398, -0.0042129415, -0.006772526, -0.0014527022, 0.017453272, 0.008203908, -0.008591378, -0.007890596, -0.008816542, -0.011198849, 0.0123248715, -0.018462248, -0.007924839, -0.018584432, 0.005128001, 0.010625549, -0.01256877, 0.00047190115, -0.0028627287, 0.0023117273, 0.006307459, 0.000130333, -0.0024540473, 0.010819244, -0.009615495, 4.2771608e-06, -0.0039122407, -0.0069461227, 0.014152672, -0.0077158823, 0.0031795152, 0.016335135, 0.012950836, 0.006546699, -0.006409383, -0.018940708, 0.008812129, -0.0045251395, 0.0012503491, -0.0070194984, -0.001662609, -0.007452628, 0.0067356275, -0.0082914075, 0.016669858, -2.6210924e-05, -0.006933464, -0.0018965001, -0.0027337354, -0.004846532, -0.011474368, 0.006269786, 0.017339522, -0.020222366, 0.023625657, -0.01132935, 0.013013303, 0.010826878, -0.0049339957, 9.863183e-05, -0.009153221, 0.016840462, 0.001515666, -0.011130265, 0.009657534, 0.007494562, -0.017683357, -0.012409279, -0.0065253577, 0.0272059, 0.0041141594, 0.0070172627, 0.0072878054, -0.0013289405, 0.018840423, -0.0038238552, -0.01052802, -0.006270675, -0.004717965, -0.00074566324, -0.015815409, 0.022260195, -0.023279194, 0.007730113, 0.0074703433, 0.0001645545, 0.010985069, -0.010077686, -0.01033176, 0.004140675, 0.00095611805, 0.012087219, 0.013893862, 0.006385951, 0.014613014, -4.8623286e-05, -0.007418765, 0.028991042, -0.0022292766, -0.011528854, -0.001975888, 0.02200185, -0.008178382, 0.010882688, -0.0013145217, -0.001429462, 0.012424344, 0.01002273, -0.00080628315, -8.530193e-05, -0.013525425, -0.015293566, -0.004981207, 0.02283793, 0.022622785, -0.0008229303, -0.0061883326, -0.022156613, -0.009912145, -0.021835478, -0.0042820508, 0.0026318177, 0.0018999677, 0.00032059036, 0.0013237195, -0.0074106064, 0.011969697, -0.015115799, 0.0176941, -0.0025104713, -0.0042676497, 0.029033527, 0.0028433278, -0.0132090105, -0.005413497, -0.01030991, -0.0043217423, 0.00015155209, -0.012222933, 0.017537156, -0.008083378, 0.002918111, 0.008267393, 0.020015126, 0.007960716, -0.004473114, 0.015448624, 0.0058753295, 0.017381689, 0.0024233663, -0.02554882, -0.0056499634, -0.020087795, 0.021648463, -0.015034387, 0.0066016885, -0.018620148, 0.02271657, -0.0034469557, -0.010793741, -0.01979357, -0.00722184, -0.012116436, -0.004930215, 0.0057647903, -0.0155866975, 0.01421693, -0.00975728, 0.005171771, -0.023575108, 0.013951452, -0.009691328, 0.10012961, 0.0062976168, -0.015889866, 0.0145693375, -0.0050303596, -0.009723008, -0.0069228476, -0.003943264, 0.019932762, -0.0054075327, -0.008848045, 0.0042091478, 0.0121685155, -0.012180075, 0.0061783646, 0.017383859, -0.0067798947, 0.011226641, 0.016885282, 0.012875306, -0.0073003257, -0.010339416, -0.028551294, -0.0074942983, 0.014704911, -0.0024342479, -0.00818616, 0.013910107, -0.015830852, -0.0073849875, -8.424664e-05, 0.015963873, 0.01000235, 0.021975238, -0.030433265, -0.0023855865, -0.012831051, 0.009442759, -0.00053344807, 0.01783634, 0.0066945497, -0.012147268, -0.0019082327, 0.0018943516, 0.015125685, 0.0019370154, -0.018201895, 0.0012249678, 0.0054869177, -0.00013557033, -0.022472003, -0.0070315218, -0.005254576, -0.00030703205, -0.026290437, -0.0074402583, -0.013735835, 0.004494601, -0.0049331696, 0.0015960805, -0.008357924, 0.023937026, 0.0011745176, -0.018194435, 0.020481441, -0.03597828, 0.0066237617, 0.007214969, -0.0045772456, -0.0006035349, -0.007014859, 0.002714582, -0.018023385, 0.012804918, 0.0374028, -0.00048165297, 0.009165267, 0.009264877, 0.0016709457, -0.013654774, -0.0062781135, 0.0057280557, -0.022542303, 0.0211295, -0.0002050706, 0.0066060806, 0.003196232, 0.012481841, 0.022677736, 0.0019363605, 0.0006822282, 0.011378161, 0.00776154, -0.0072235144, -0.0208973, 0.00053953263, 0.03406599, 0.024962192, 0.009006513, 0.003813372, 0.001429719, -0.008517629, 0.0046529244, -0.004130572, 0.0019879371, -0.0068838983, 0.020036636, 0.0048898594, -0.003897793, -0.0069703003, -0.012515182, 0.0018305784, 0.0116930455, -0.01862459, -0.017302118, -0.013342886, 0.0054883505, 0.012875103, -0.0034702185, -0.0110882055, 0.005671331, -0.008505791, -0.0037588917, -0.005743798, 0.004718313, 0.0006911055, 0.0025198427, -0.015275109, 0.0021800103, 0.0024722607, -0.0036026752, -0.0053730076, 0.004626033, 0.013763397, 0.0026177147, -0.010137875, 0.017940763, -0.012060978, 0.0052029807, 0.0031969, -0.003210532, -0.009586115, -0.0109801525, 0.01223202, -0.012590357, 0.010315635, 0.0071757534, 0.019175196, 0.0047344714, -0.014871977, -0.009657546, 0.0047394033, -0.00066265615, 0.021351868, 0.00065542967, -0.0049886997, -0.0064289737, 0.005465339, 0.021675566, -0.009679036, 0.0008622312, 0.007102327, -0.015599464, 0.0047104126, 0.01411112, -0.014381866, 0.018731898, 0.013077989, -0.007814516, 0.0077549717, 0.0039814594, 0.0016393797, 0.006483502, 0.019608298, -0.0040442725, -0.010840601, 0.0039398964, -0.00904353, -0.010484723, 0.0131693715, 0.00091828825, 0.0077772527, -0.006661444, -0.015615529, -0.01620837, -0.0044510174, 0.0027787297, 0.009869081, 0.0052285646, -0.016990192, 0.010726238, -0.011738896, 0.016624099, 0.0021085553, 0.0050365413, 0.004036475, 0.007853955, 0.0007825487, 0.024461668, -0.0017388159, 0.008859641, -0.005332805, 0.0030660538, -0.014448851, -0.0055502816, 0.0010537386, 0.00952076, -0.0033602747, -0.0079411045, 0.0010778786, -0.013958611, -0.01595714, -0.0064774523, -0.0022057372, 0.0040657544, -0.021970164, 0.009075279, -0.007732621, 0.002725589, -0.033089593, -0.0007069498, -0.0036494571, -0.012022506, -0.0062126936, -0.003418526, -0.009111056, 0.009528491, 0.015674584, -0.0026817813, -0.0035888413, -0.010323761, 0.009900434, -0.006006784, -0.005880026, -0.014339324, -0.01077301, -0.0026568747, -0.007045839, -0.0018369431, -0.0032456354, -0.00959038, -0.00469801, -0.011002627, 0.0015359371, 0.0041608606, 0.0047749043, -0.025435746, 0.0026556416, -0.017803764, 0.0073956195, -0.0035532075, -0.008962402, -0.004309239, -0.007921533, 0.021631999, 0.004593853, -0.0011033573, -0.057735797, 0.011308499, 0.029778436, -0.0037832975, 0.0046552285, -0.016427238, -0.013150297, -0.00066672725, 0.0034801387, -0.019164216, 0.004009139, -0.0039558457, -0.0055567506, 0.012075053, -0.012620812, 0.008329398, -0.012083543, -0.008001708, 0.010204328, -0.02213557, -0.017059673, -0.00041685594, -0.016230369, -0.009085095, 0.008462155, -0.008267353, -0.003968127, -0.013904617, 0.002581124, -0.009614241, 0.0055493647, -0.0113572925, -0.00840578, -0.0018162557, 0.0046588164, 0.012750404, 0.015226099, 0.0069431486, 0.010541205, -0.0022874386, 0.014020607, 0.00837326, 0.005508288, 0.0067696897, -0.0034883237, 0.0032518443, 0.0009434949, 0.0042537632, 0.003998888, 0.0024890667, 0.0028994903, 0.004475612, -0.012964595, 0.010567403, 0.00077506085, -0.012652642, 0.019522369, 0.0100732045, 0.015418142, 0.011421512, -0.011522957, 0.011377052, 0.010441017, -0.005439585, 0.012708712, -0.017522587, 0.021018157, -0.007692411, -0.007000218, 0.0077785607, 0.004063796, 0.008401302, 0.006243087, -0.008651107, -0.010470854, -0.00095372257, 0.010618584, 0.00016037741, -0.005336165, 0.0023558235, 0.017910875, 0.021321343, -0.009250161, -0.0061048707, -0.01083175, -0.0023877441, -0.0008870281, -0.010995512, -0.014362618, 0.008347319, -0.0017112287, -0.0017289972, 0.009067665, 0.008350115, -0.01729993, 0.007994131, -0.02592562, 1.3194393e-05, -0.0033268875, 0.012971678, -0.010175376, -0.0008046995, -0.0035830722, 0.021552278, -0.01699868, 0.0097788805, 0.0067401826, 0.00107148, 0.0029923532, -0.010853015, -0.0046046344, 0.0063964613, 0.004810429, -0.0040766564, 0.0034204868, -0.004712799, -0.00082314445, -0.0053997273, -0.014199309, 0.00051455165, -0.006772377, 0.01206133, 0.00035917273, -0.0015326628, 0.024106206, -0.0027313994, -0.01250123, -0.0029785605, 0.0054488983, 0.00080960884, -0.0032941494, -0.002103455, 0.0003873014, -0.0046384432, -0.005599933, -0.006259594, 0.011128274, 0.004698649, 0.0017032715, 0.006367227, 0.0056207967, -0.012770958, 0.00020126635, 0.00933709, -0.010181467, -0.0017322302, -0.008596564, -0.00028898628, 0.00589864, 0.0036192944, 0.0036049015, 0.0004933945, 0.0022308882, 0.016618367, -0.00719637, -0.0009898667, 0.00721423, -0.0025690598, -0.0019313983, -0.021590699, 0.027407115, -0.0103648305, 0.0027273982, -0.009715373, 0.0016588526, -0.015943827, -0.0020987766, 0.004277991, 0.0015068139, -0.016529765, 0.022760315, 0.0061575933, 0.01261183, 0.014368483, 0.010308367, 0.023171691, 0.015491863, -0.0025825836, -0.016185286, 0.03340457, 0.009656783, 0.009220873, 0.0024612125, -0.00025300597, -0.0056465315, -0.0027562045, 0.002254101, 0.008468921, -0.005928149, -0.002515439, 0.008197037, -0.0036411097, -0.006031576, -0.009190429, 0.0011758739, -0.0033515524, 0.009769092, -0.0024888145, 0.0060550724, -0.0050962875, -0.0048158765, -0.0023141801, 0.01126418, -0.0010586554, 0.00737895, -0.09774056, 0.011948981, -0.008664701, 0.0016215204, -0.012398039, -0.015465362, 0.0110492045, -0.007495368, -0.015606894, -0.0039120307, -0.012274593, 0.018148117, 0.005010056, -0.010635065, 0.0158104, -0.0052569755, -0.006785043, 0.014028051, 0.0008611148, -0.01413768, -0.001834428

In [10]:
print(result['embedding'])

[[-0.006957309, 0.015669828, -0.002305022, -0.05786128, 0.023529692, 0.021365006, -0.0048412452, -0.010775757, -0.037184883, -0.006749296, -0.05041439, -0.010716306, 0.00018510461, -0.007115277, 0.11918452, -0.016847137, 0.014053316, 0.0037684322, 0.0012318222, -0.019463938, -0.0091748675, 0.014780136, 0.004766676, -0.0023347707, -0.022118734, -0.030557282, 0.035106838, 0.030003343, 0.042310067, 0.0007536542, 0.0010637754, 0.02587698, 0.0078955535, 0.0282977, -0.0031126952, 0.023079716, -0.010645984, 0.0008762546, -0.013065552, 0.016391497, 0.008287095, 0.014236358, -0.017534593, -0.020157427, -0.008688459, -0.009051389, -0.006668721, 0.0042255097, -0.0076902406, 0.021984987, -0.01772308, 0.01311187, -0.007437147, -0.19306765, -0.0048237303, -0.027916854, 0.006469652, -0.0028410193, 0.01916372, -0.028317709, 0.0011445108, 0.027103094, -0.046611074, -0.028726097, -0.009938895, -0.026199052, 0.0010534151, -0.005843079, 0.02205556, -0.019225411, 0.004598728, 0.0069517074, -0.0026115673, -0.03148483, -0.0052708876, -0.029789438, -0.0044351704, -0.021154126, 0.012814803, -0.0030102835, -0.021098362, -0.019691022, 0.006589136, -0.018243307, 0.012318603, -0.015774535, 0.0074369637, 0.021156948, -0.019812785, 0.023866039, 0.005660511, 0.034419365, -0.0072480356, -0.025951471, 0.0058726543, -0.00260082, 0.009396817, -0.008850699, -0.0015216726, -0.002283233, -0.014574505, -0.029328248, 0.007475457, -0.0060906666, 0.020453634, 0.0003087988, 0.015386449, -0.012823073, 0.018502323, 0.0016649406, 0.026398726, 0.011656987, -0.0019358371, 0.0024599936, 0.0144286845, -0.14411634, 0.008377012, 0.013190595, 0.0018847685, -0.01302812, -0.023854386, -0.032347646, -0.00107325, 0.003671256, 0.0054504075, -0.012583231, 0.014545558, -0.010788116, -0.0029257466, 0.021056337, -0.033926614, -0.035342798, 0.007873551, -0.013206373, 0.026540905, 0.012513233, -0.016148603, 0.0010202997, -0.010420467, -0.040178932, 0.016246047, 0.0019929528, -0.010983823, 0.012223829, -0.02620297, -0.010236148, -0.022190329, -0.023381555, -0.011321529, -0.029463202, -0.012903906, -0.013764899, -0.0044145063, -0.011079903, 0.0141564235, -0.014330737, 0.0028677438, 0.023255784, -0.02871454, -0.022105947, 0.0041162274, 0.010466678, -0.000112133894, 0.006979115, 0.009751928, -0.00071152765, 0.018760612, 0.012345246, -0.017813923, 0.0073928963, 0.018152546, 0.0064031244, 0.005509517, -0.001335606, -0.011505305, -0.019824637, -0.0036490848, -0.0006174745, 0.019013777, -0.019193154, -0.00090558187, -0.01663853, -0.009790892, 0.013635551, 0.0181677, 0.0029787775, 0.007339864, 0.010203617, 0.017088145, 0.015353683, -0.02050618, 0.013611949, 0.0046169376, -0.008143069, -0.018650427, -0.027794288, -0.01733395, 0.0021845785, -0.009520841, 0.030529331, 0.02044791, 0.012316591, 0.0006312857, -0.006613526, 0.021094635, 0.009558974, -0.017397474, 0.0133248065, 0.0066456255, 0.03162709, 0.004495852, 0.021490376, 0.0070809573, 0.00090470404, 0.011781733, -0.033968277, -0.017516246, -0.009622809, -0.0022691053, 0.0032460298, 0.009731705, 0.0026974971, 0.008519563, 0.030932203, -0.0013929037, -0.006570089, 0.02161323, -0.033569574, 0.014153057, -0.015558878, -0.00020521255, 0.007661265, -0.00279087, 0.016522836, 0.027558742, -0.023080433, 0.0029092375, 0.015251797, -0.0009400235, 0.027693642, 0.006724716, -0.032711055, -0.00016345487, 0.0035831358, 0.012997335, -0.0046951165, 0.0075284163, -0.015683673, -0.0029373353, 0.01630179, -0.020581407, 0.0013299892, -0.003841935, -0.01769441, -0.030536652, 0.031101616, 0.0008907687, -0.015118233, 0.009263769, -0.019895134, -0.021494253, 0.009243289, -0.0076835025, -0.011897752, -0.0048949653, 0.0074055013, 0.015766434, 0.013714811, -0.0110406885, -0.0054062963, 0.0028140678, -0.00487227, -0.017888013, 0.0016033452, 0.015256297, 0.000409635, -0.05827096, 0.025613658, 0.0091681825, -0.01937675, -0.030638877, 0.003576104, 0.028409231, -0.0075114653, 0.0023306145, 0.03187954, -0.0035543516, -0.006887985, 0.025248004, -0.011044169, 0.0013929872, -0.015678875, -0.008823701, 0.0026428027, 0.0043640067, -0.0068541574, 0.000108455475, -0.0025795538, 0.008587824, -0.024126664, 0.0076350463, -0.02640558, 0.012395046, 0.04841188, 0.0057653924, -0.00662543, 0.007996116, 0.037285924, -0.009713399, -0.0023247777, 0.010739214, 0.030287469, 0.017888304, -0.00014110988, 0.0036735993, 0.011221185, 0.04596454, 0.0029750492, -0.0063028443, -0.006647099, -0.0014908027, 0.015920667, -0.028078724, 0.023184774, -0.011430571, 0.018228771, -0.010094402, 0.017828176, -0.013510195, 0.00043033497, 0.011357273, 0.011346833, -0.016109336, -0.006331869, 0.026737766, 0.018367754, 0.0016630401, -0.004468436, 0.004337949, 0.02103938, 0.020943947, 0.015236904, -0.031120546, 0.014274784, -0.03757023, 0.008687874, 0.019478956, -0.009532437, 0.010738215, 0.007057664, -0.01623906, -0.009992156, 0.0021420682, -0.00078018766, -0.0213094, 0.00048825078, 0.003038082, -0.009535905, -0.0010332714, 0.026909126, 0.0090365345, -0.0028713525, -0.020069394, 0.009168701, 0.006166015, -0.014362823, 0.002947943, 0.008746861, -0.008117606, -0.0038933868, -0.022357078, 0.0055316295, 0.012608725, -0.019616658, -0.029031893, 0.0019272306, -0.0027843835, 0.014144194, 0.012072879, 0.007380538, -0.0244136, 0.008989904, 0.006218713, -0.00061965716, 0.0088014975, 0.003503869, 0.019393235, 0.006576538, 0.010337435, 0.01413529, -0.004666979, 0.014876828, 0.0120347915, -0.0072819646, -0.0061727664, -0.014646434, -0.0013495507, -0.0053897155, -0.011082851, 0.014597513, -0.015419381, 0.011139686, -0.032421857, 0.011327202, -0.011090442, 0.0077604474, 0.021720381, -0.01978818, 0.0070183896, -0.0006406451, 0.013028441, 0.01073349, -0.0013911017, -0.015720885, 0.010608837, -0.01141159, -0.010460157, 0.003649222, 0.01845978, -0.014758722, 0.020884693, -0.0076889526, -0.011219743, 0.0016219029, 0.016802914, 0.013149691, -0.016746225, -0.012982723, -0.018292911, 0.0038944902, 0.014947065, -0.0005406652, -0.01797119, -0.026920985, -0.028709097, -0.013983697, -0.019278215, 0.00791074, -0.02837031, 0.0045763636, -0.004020105, 0.017748497, -0.016729258, -0.0051218597, 0.032312192, -0.009404596, 0.018061645, -0.01969009, -0.013479107, -0.02295197, 0.006102712, 0.0075784344, -0.01534882, -0.010011492, 0.012054755, 0.010477768, -0.017026795, -0.010900024, -0.014305251, -0.004126734, 0.00081447186, 0.011834731, 0.013867212, 0.008115558, 0.001018451, -0.0068152235, -0.00061402895, -0.007193424, 0.016048241, 0.021828603, -0.00875956, -0.0016615867, -0.0152747035, -0.03213149, 0.012043393, -0.028146384, -0.0077240192, -0.029450214, 0.021437638, 0.015906373, 0.0082409745, -0.0037599308, 0.0021780846, -0.0012635122, -0.008610907, 0.0043145358, -0.01200724, 0.00751163, -0.0062006037, 0.0025174369, 0.017537294, 0.02212468, -0.015253419, 0.008937966, -0.04649194, 0.014861212, 0.020900141, 0.030753085, 0.022856658, 0.0077218935, -0.014415543, 0.0072064092, -0.014147817, 0.009112485, -0.0009659889, -0.005192122, 0.013186235, -0.0044482583, 0.0038130577, 0.0032619282, 0.00048251107, -0.003249979, -0.024061056, 0.037434157, -0.018431876, 0.0013780429, 0.0032618036, 0.011703706, 0.021091403, -0.023877747, -0.023401175, 0.014872387, -0.014068313, 0.006770194, 0.008052453, 0.013485705, -0.0003951377, -0.005422259, 0.022045504, -0.029803464, -0.01028315, 0.0367672, -0.02710332, -0.027690396, 0.004844998, -0.010683812, -0.009076664, 0.030086676, 0.0017607885, 0.0059857564, -0.03776797, -0.0028822746, -0.011710007, 0.0061040944, -0.021320846, -0.11777184, -0.008099914, 0.016491333, -4.5193206e-05, -0.001130553, -0.009292864, -0.0015350928, 0.024535283, -0.012586336, -0.00468004, 0.012458158, 0.007288378, -0.00055591593, -0.008151375, -0.010474431, -0.023087569, -0.0128946565, 0.001283177, -0.0018810987, -0.023517186, -0.019398764, 0.017950654, 0.011261478, -0.020438543, 0.010990099, -0.012188055, 0.013025339, 0.003183992, -0.0011437347, 0.017643917, -0.014091024, 0.0013353154, 0.0010131837, 0.047339283, -0.0069637783, -0.0038840552, 0.0010821765, -0.030030899, 0.015363363, -0.018199574, 0.004674435, 0.0016789743, -0.003156738, -0.019701408, 0.013089889, 0.01583575, 0.0037070836, -0.02089062, 0.02730666, 0.0046813847, -0.021381725, -0.012013705, -0.02650883, -0.006970858, 0.028286267, 0.00075734104, -0.03375607, 0.033477943, -0.032958522, 0.011002776, -0.03649155, 0.00043788663, -0.0018156633, 0.028502112, 0.003530113, 0.018935088, 0.0021837116, -0.0014462505, -0.015171538, -5.570354e-05, -0.034273416, -0.05368163, 0.0018897044, 0.015493302, -0.028471168, -0.029503101, 0.008460158, 0.054621425, 0.00062822166, -0.006551077, 0.009617354, 0.0026791778, -0.069115154, 0.009591412, -0.010802567, -0.010600622, 0.013948249, 0.005206551, 0.018235076, -0.023864219, -0.020203676, 0.0072875465, 0.003783323, -0.008092805, 0.018910727, -0.011774473, 0.04001247, 0.014837539, -0.011575248, 0.010044691, -0.026091367, -0.018618457, -0.008455403, 0.009378545, -0.0028360656, 0.0007577961, -6.90395e-05, 0.005739788, 0.022605719, -0.0073750955, 0.008133341, -0.031555887, -0.0031582438, -0.16355214, 0.010529357, -0.027211448, 0.031537287, 0.0072207884, 0.015796484, 0.025416654, 0.0050912974, -0.008097813, -0.019020814, 0.017622676, -0.05231363, -0.047150627, -0.0052467547, 0.010050182, 0.08819803, -0.011349501, -0.00932716, -0.01324242, -0.011686042, -0.0066335374, -0.015062125, -0.0073319497, -0.0070075756, -0.011213317, -0.014392903, -0.013686686, 7.829488e-05, 0.0131067205, 0.0112530645, 0.0029807459, -0.01330456, -0.011923888, 0.011842413, -0.013879762, -0.012015627, 0.017920908, -0.009755646, -0.011297928, 0.01021835, 0.023353502, 0.017723445, 0.014491105, -0.018726232, -0.003976626, -5.3549476e-05, 0.0030852463, -0.005279204, 0.012509754, -0.011669444, -0.02992691, -0.050057784, -0.0067745396, 0.0075399294, 0.034603156, -0.0007848108, -0.015554789, 0.004279748, -0.003479841, -0.004537522, 0.009372092, 0.017952833, 0.01749478, 0.03704984, -0.023933817, -0.0011843764, 0.025904458, 0.0122597525, -0.02254661, -0.008271346, 0.022395398, 0.00018988502, 0.009094417, -0.0013342076, -0.008706739, -0.020677213, 0.0065759937, -0.013738922, -0.006125026, -0.012289529, -0.015012152, 0.010692073, 0.029661218, -0.02834397, -0.049146604, 0.010002875, 0.009288483, 0.02703869, 0.0015956092, -0.004894015, 0.009934602, 0.04448145, 0.0008698589, -0.009765205, -0.007260715, -0.011940574, 0.011744918, 0.01863586, -0.020236917, -0.020724298, 0.029906096, -0.012775816, -0.010328664, -0.020885378, -0.034516636, 0.0007573511, 0.02835182, -0.019815212, 0.033684026, 0.007923781, 0.0037525564, -0.009772003, -0.0024253007, 0.0048570475, 0.0010126968, -0.0039377315, 0.0076698987, -0.0038846233, -0.0019183815, -0.0058784913, 0.0038078167, 0.015233998, -0.0062239002, 0.013715375, 0.010206204, -0.0019078121, -0.0021470946, -0.00047623282, 0.0064562913, -0.026592268, 0.007725181, -0.012191913, -0.0006115777, 0.0010003304, 0.00090676546, 0.0039481116, 0.0018484518, -0.00031211803, 0.0008182398, -0.0042129415, -0.006772526, -0.0014527022, 0.017453272, 0.008203908, -0.008591378, -0.007890596, -0.008816542, -0.011198849, 0.0123248715, -0.018462248, -0.007924839, -0.018584432, 0.005128001, 0.010625549, -0.01256877, 0.00047190115, -0.0028627287, 0.0023117273, 0.006307459, 0.000130333, -0.0024540473, 0.010819244, -0.009615495, 4.2771608e-06, -0.0039122407, -0.0069461227, 0.014152672, -0.0077158823, 0.0031795152, 0.016335135, 0.012950836, 0.006546699, -0.006409383, -0.018940708, 0.008812129, -0.0045251395, 0.0012503491, -0.0070194984, -0.001662609, -0.007452628, 0.0067356275, -0.0082914075, 0.016669858, -2.6210924e-05, -0.006933464, -0.0018965001, -0.0027337354, -0.004846532, -0.011474368, 0.006269786, 0.017339522, -0.020222366, 0.023625657, -0.01132935, 0.013013303, 0.010826878, -0.0049339957, 9.863183e-05, -0.009153221, 0.016840462, 0.001515666, -0.011130265, 0.009657534, 0.007494562, -0.017683357, -0.012409279, -0.0065253577, 0.0272059, 0.0041141594, 0.0070172627, 0.0072878054, -0.0013289405, 0.018840423, -0.0038238552, -0.01052802, -0.006270675, -0.004717965, -0.00074566324, -0.015815409, 0.022260195, -0.023279194, 0.007730113, 0.0074703433, 0.0001645545, 0.010985069, -0.010077686, -0.01033176, 0.004140675, 0.00095611805, 0.012087219, 0.013893862, 0.006385951, 0.014613014, -4.8623286e-05, -0.007418765, 0.028991042, -0.0022292766, -0.011528854, -0.001975888, 0.02200185, -0.008178382, 0.010882688, -0.0013145217, -0.001429462, 0.012424344, 0.01002273, -0.00080628315, -8.530193e-05, -0.013525425, -0.015293566, -0.004981207, 0.02283793, 0.022622785, -0.0008229303, -0.0061883326, -0.022156613, -0.009912145, -0.021835478, -0.0042820508, 0.0026318177, 0.0018999677, 0.00032059036, 0.0013237195, -0.0074106064, 0.011969697, -0.015115799, 0.0176941, -0.0025104713, -0.0042676497, 0.029033527, 0.0028433278, -0.0132090105, -0.005413497, -0.01030991, -0.0043217423, 0.00015155209, -0.012222933, 0.017537156, -0.008083378, 0.002918111, 0.008267393, 0.020015126, 0.007960716, -0.004473114, 0.015448624, 0.0058753295, 0.017381689, 0.0024233663, -0.02554882, -0.0056499634, -0.020087795, 0.021648463, -0.015034387, 0.0066016885, -0.018620148, 0.02271657, -0.0034469557, -0.010793741, -0.01979357, -0.00722184, -0.012116436, -0.004930215, 0.0057647903, -0.0155866975, 0.01421693, -0.00975728, 0.005171771, -0.023575108, 0.013951452, -0.009691328, 0.10012961, 0.0062976168, -0.015889866, 0.0145693375, -0.0050303596, -0.009723008, -0.0069228476, -0.003943264, 0.019932762, -0.0054075327, -0.008848045, 0.0042091478, 0.0121685155, -0.012180075, 0.0061783646, 0.017383859, -0.0067798947, 0.011226641, 0.016885282, 0.012875306, -0.0073003257, -0.010339416, -0.028551294, -0.0074942983, 0.014704911, -0.0024342479, -0.00818616, 0.013910107, -0.015830852, -0.0073849875, -8.424664e-05, 0.015963873, 0.01000235, 0.021975238, -0.030433265, -0.0023855865, -0.012831051, 0.009442759, -0.00053344807, 0.01783634, 0.0066945497, -0.012147268, -0.0019082327, 0.0018943516, 0.015125685, 0.0019370154, -0.018201895, 0.0012249678, 0.0054869177, -0.00013557033, -0.022472003, -0.0070315218, -0.005254576, -0.00030703205, -0.026290437, -0.0074402583, -0.013735835, 0.004494601, -0.0049331696, 0.0015960805, -0.008357924, 0.023937026, 0.0011745176, -0.018194435, 0.020481441, -0.03597828, 0.0066237617, 0.007214969, -0.0045772456, -0.0006035349, -0.007014859, 0.002714582, -0.018023385, 0.012804918, 0.0374028, -0.00048165297, 0.009165267, 0.009264877, 0.0016709457, -0.013654774, -0.0062781135, 0.0057280557, -0.022542303, 0.0211295, -0.0002050706, 0.0066060806, 0.003196232, 0.012481841, 0.022677736, 0.0019363605, 0.0006822282, 0.011378161, 0.00776154, -0.0072235144, -0.0208973, 0.00053953263, 0.03406599, 0.024962192, 0.009006513, 0.003813372, 0.001429719, -0.008517629, 0.0046529244, -0.004130572, 0.0019879371, -0.0068838983, 0.020036636, 0.0048898594, -0.003897793, -0.0069703003, -0.012515182, 0.0018305784, 0.0116930455, -0.01862459, -0.017302118, -0.013342886, 0.0054883505, 0.012875103, -0.0034702185, -0.0110882055, 0.005671331, -0.008505791, -0.0037588917, -0.005743798, 0.004718313, 0.0006911055, 0.0025198427, -0.015275109, 0.0021800103, 0.0024722607, -0.0036026752, -0.0053730076, 0.004626033, 0.013763397, 0.0026177147, -0.010137875, 0.017940763, -0.012060978, 0.0052029807, 0.0031969, -0.003210532, -0.009586115, -0.0109801525, 0.01223202, -0.012590357, 0.010315635, 0.0071757534, 0.019175196, 0.0047344714, -0.014871977, -0.009657546, 0.0047394033, -0.00066265615, 0.021351868, 0.00065542967, -0.0049886997, -0.0064289737, 0.005465339, 0.021675566, -0.009679036, 0.0008622312, 0.007102327, -0.015599464, 0.0047104126, 0.01411112, -0.014381866, 0.018731898, 0.013077989, -0.007814516, 0.0077549717, 0.0039814594, 0.0016393797, 0.006483502, 0.019608298, -0.0040442725, -0.010840601, 0.0039398964, -0.00904353, -0.010484723, 0.0131693715, 0.00091828825, 0.0077772527, -0.006661444, -0.015615529, -0.01620837, -0.0044510174, 0.0027787297, 0.009869081, 0.0052285646, -0.016990192, 0.010726238, -0.011738896, 0.016624099, 0.0021085553, 0.0050365413, 0.004036475, 0.007853955, 0.0007825487, 0.024461668, -0.0017388159, 0.008859641, -0.005332805, 0.0030660538, -0.014448851, -0.0055502816, 0.0010537386, 0.00952076, -0.0033602747, -0.0079411045, 0.0010778786, -0.013958611, -0.01595714, -0.0064774523, -0.0022057372, 0.0040657544, -0.021970164, 0.009075279, -0.007732621, 0.002725589, -0.033089593, -0.0007069498, -0.0036494571, -0.012022506, -0.0062126936, -0.003418526, -0.009111056, 0.009528491, 0.015674584, -0.0026817813, -0.0035888413, -0.010323761, 0.009900434, -0.006006784, -0.005880026, -0.014339324, -0.01077301, -0.0026568747, -0.007045839, -0.0018369431, -0.0032456354, -0.00959038, -0.00469801, -0.011002627, 0.0015359371, 0.0041608606, 0.0047749043, -0.025435746, 0.0026556416, -0.017803764, 0.0073956195, -0.0035532075, -0.008962402, -0.004309239, -0.007921533, 0.021631999, 0.004593853, -0.0011033573, -0.057735797, 0.011308499, 0.029778436, -0.0037832975, 0.0046552285, -0.016427238, -0.013150297, -0.00066672725, 0.0034801387, -0.019164216, 0.004009139, -0.0039558457, -0.0055567506, 0.012075053, -0.012620812, 0.008329398, -0.012083543, -0.008001708, 0.010204328, -0.02213557, -0.017059673, -0.00041685594, -0.016230369, -0.009085095, 0.008462155, -0.008267353, -0.003968127, -0.013904617, 0.002581124, -0.009614241, 0.0055493647, -0.0113572925, -0.00840578, -0.0018162557, 0.0046588164, 0.012750404, 0.015226099, 0.0069431486, 0.010541205, -0.0022874386, 0.014020607, 0.00837326, 0.005508288, 0.0067696897, -0.0034883237, 0.0032518443, 0.0009434949, 0.0042537632, 0.003998888, 0.0024890667, 0.0028994903, 0.004475612, -0.012964595, 0.010567403, 0.00077506085, -0.012652642, 0.019522369, 0.0100732045, 0.015418142, 0.011421512, -0.011522957, 0.011377052, 0.010441017, -0.005439585, 0.012708712, -0.017522587, 0.021018157, -0.007692411, -0.007000218, 0.0077785607, 0.004063796, 0.008401302, 0.006243087, -0.008651107, -0.010470854, -0.00095372257, 0.010618584, 0.00016037741, -0.005336165, 0.0023558235, 0.017910875, 0.021321343, -0.009250161, -0.0061048707, -0.01083175, -0.0023877441, -0.0008870281, -0.010995512, -0.014362618, 0.008347319, -0.0017112287, -0.0017289972, 0.009067665, 0.008350115, -0.01729993, 0.007994131, -0.02592562, 1.3194393e-05, -0.0033268875, 0.012971678, -0.010175376, -0.0008046995, -0.0035830722, 0.021552278, -0.01699868, 0.0097788805, 0.0067401826, 0.00107148, 0.0029923532, -0.010853015, -0.0046046344, 0.0063964613, 0.004810429, -0.0040766564, 0.0034204868, -0.004712799, -0.00082314445, -0.0053997273, -0.014199309, 0.00051455165, -0.006772377, 0.01206133, 0.00035917273, -0.0015326628, 0.024106206, -0.0027313994, -0.01250123, -0.0029785605, 0.0054488983, 0.00080960884, -0.0032941494, -0.002103455, 0.0003873014, -0.0046384432, -0.005599933, -0.006259594, 0.011128274, 0.004698649, 0.0017032715, 0.006367227, 0.0056207967, -0.012770958, 0.00020126635, 0.00933709, -0.010181467, -0.0017322302, -0.008596564, -0.00028898628, 0.00589864, 0.0036192944, 0.0036049015, 0.0004933945, 0.0022308882, 0.016618367, -0.00719637, -0.0009898667, 0.00721423, -0.0025690598, -0.0019313983, -0.021590699, 0.027407115, -0.0103648305, 0.0027273982, -0.009715373, 0.0016588526, -0.015943827, -0.0020987766, 0.004277991, 0.0015068139, -0.016529765, 0.022760315, 0.0061575933, 0.01261183, 0.014368483, 0.010308367, 0.023171691, 0.015491863, -0.0025825836, -0.016185286, 0.03340457, 0.009656783, 0.009220873, 0.0024612125, -0.00025300597, -0.0056465315, -0.0027562045, 0.002254101, 0.008468921, -0.005928149, -0.002515439, 0.008197037, -0.0036411097, -0.006031576, -0.009190429, 0.0011758739, -0.0033515524, 0.009769092, -0.0024888145, 0.0060550724, -0.0050962875, -0.0048158765, -0.0023141801, 0.01126418, -0.0010586554, 0.00737895, -0.09774056, 0.011948981, -0.008664701, 0.0016215204, -0.012398039, -0.015465362, 0.0110492045, -0.007495368, -0.015606894, -0.0039120307, -0.012274593, 0.018148117, 0.005010056, -0.010635065, 0.0158104, -0.0052569755, -0.006785043, 0.014028051, 0.0008611148, -0.01413768, -0.0018344283, 0.010838062

In [11]:
def embed_text(text: str) -> np.ndarray:
    resp = call_with_retry(
        genai.embed_content,
        model="gemini-embedding-001",
        content=text,
        task_type=task_type,   # "retrieval_query" or "retrieval_document"
    )
    return np.asarray(resp["embedding"], dtype=np.float32)

In [12]:
df['Embeddings'] = df['Text'].apply(embed_text)
df

,Title,Text,Embeddings
0,Onboarding Guide,# Brightdesk — New Hire Onboarding Guide ## B...,"[-0.0075476617, 0.016903909, -0.001111857, -0...."
1,Leave and Vacation Policy,# Brightdesk — Leave & Vacation Policy ## Pai...,"[0.004197855, 0.026593978, 0.0062915646, -0.05..."
2,Health Insurance and Benefits,# Brightdesk — Health Insurance & Benefits ##...,"[-0.022602076, 0.024628248, -0.003922993, -0.0..."
3,Remote and Hybrid Work Policy,# Brightdesk — Remote & Hybrid Work Policy ##...,"[0.00039880569, 0.016733184, 0.005057843, -0.0..."

In [13]:
def query_similarity_score(query,vector):
    # query --> 'How can I take a sick leave?' TEXT STR
    # vector --> our existing Array (list)

    # Query STR --> LIST
    query_embedding = embed_text(query)

    #SIMILARITY
    return np.dot(query_embedding,vector)

In [14]:
query = "Скільки в мене на рік доступно вихідних?"
df['Similarity'] = df['Embeddings'].apply(lambda vector: query_similarity_score(query,vector))

In [15]:
df

,Title,Text,Embeddings,Similarity
0,Onboarding Guide,# Brightdesk — New Hire Onboarding Guide ## B...,"[-0.0075476617, 0.016903909, -0.001111857, -0....",0.686474
1,Leave and Vacation Policy,# Brightdesk — Leave & Vacation Policy ## Pai...,"[0.004197855, 0.026593978, 0.0062915646, -0.05...",0.766189
2,Health Insurance and Benefits,# Brightdesk — Health Insurance & Benefits ##...,"[-0.022602076, 0.024628248, -0.003922993, -0.0...",0.682433
3,Remote and Hybrid Work Policy,# Brightdesk — Remote & Hybrid Work Policy ##...,"[0.00039880569, 0.016733184, 0.005057843, -0.0...",0.706529

In [16]:
#now let`s extract `the text we need to have as context to answer our question
df.sort_values('Similarity',ascending=False)
df.sort_values('Similarity',ascending=False)[['Title','Text']]
df.sort_values('Similarity',ascending=False)[['Title','Text']].iloc[0]

Title                            Leave and Vacation Policy
Text     # Brightdesk — Leave & Vacation Policy  ## Pai...
Name: 1, dtype: object

In [17]:
def  most_similar_doc(query):
    df['Similarity'] = df['Embeddings'].apply(lambda vector: query_similarity_score(query,vector))
    title = df.sort_values('Similarity',ascending=False)[['Title','Text']].iloc[0]['Title']
    text = df.sort_values('Similarity',ascending=False)[['Title','Text']].iloc[0]['Text']
    return title,text

In [18]:
title, text = most_similar_doc('Хочу відвідати конференцію. Чи може компанія мені це покрити?')
print(title,text)

Leave and Vacation Policy # Brightdesk — Leave & Vacation Policy  ## Paid Time Off (PTO) Full-time employees accrue 24 calendar days of paid annual leave per year (the statutory minimum under Ukrainian labor law), credited at 2 days per month worked. Unused PTO up to 5 days may be carried over into the next calendar year; anything beyond that is forfeited unless local law requires otherwise.  ## Requesting Leave Submit leave requests through the HR portal at least 5 business days in advance for planned leave. Requests are approved by your direct manager. Leave taken without prior approval (except sick leave) may be recorded as unpaid.  ## Sick Leave Employees receive 10 paid sick days per year, separate from PTO. A doctor's note is required for absences longer than 3 consecutive days. Sick leave does not need to be scheduled in advance.  ## Parental Leave - Primary caregiver: 16 weeks paid leave. - Secondary caregiver: 6 weeks paid leave. Parental leave can be taken within 12 months of the birth or adoption date and does not need to be used consecutively.  ## Public Holidays Brightdesk observes 11 public holidays per year, published annually in the HR portal calendar. Employees working in a different country follow their local public holiday calendar.  ## Bereavement Leave Up to 5 paid days for the loss of an immediate family member, and 2 paid days for extended family, at manager's discretion for edge cases.

## Етап 3: Генерація відповіді

In [23]:
def rag_implement(query):
    #Retrival Document
    title,text = most_similar_doc(query)
    #AG - Model
    model = genai.GenerativeModel(MODEL_NAME)
    #Augment --> prompt engineering
    prompt = f'Answer this query:\n{query}. \n Only use this context to answer: \n{text}'
    #Sourcing(title) - what doc was used
    response = call_with_retry(model.generate_content, prompt)
    # return f'{response.text}\n\n Source Doc Title: {title}'
    return response.text,title

In [29]:
print(rag_implement('А чи є курси німецької?'))

('На основі наданого контексту інформація про курси німецької мови відсутня.', 'Leave and Vacation Policy')

## Chunking

Get the most relevant chunks to the query

In [ ]:
def get_relevant_chunks(query: str, num_chunks: int = 3):
    q = np.asarray(embed_text(query), dtype=np.float32)   # one API call
    sims = EMB_MATRIX @ q                                 # dot product vs all chunks
    top_idx = np.argsort(-sims)[:num_chunks]
    top = df_chunks.iloc[top_idx]
    return top["Text"].tolist(), top["Title"].tolist()

## Improving chunking - by split per sentence + adding preprocessing

In [ ]:
import nltk
import re
from nltk.tokenize import sent_tokenize

In [ ]:
nltk.download('punkt')
nltk.download('punkt_tab')

In [ ]:
def text_splitter(text, chunk_size=500, overlap=50):
    chunks = []
    # Ensure text is a string
    if not isinstance(text, str):
        text = str(text)

    # Preprocessing: remove extra whitespace and unnecessary symbols
    # Replace multiple spaces/newlines with a single space.
    text = re.sub(r'[\s]+', ' ', text)
    # Keep alphanumeric characters, spaces, and common punctuation.
    # Added Cyrillic character range (а-яА-Я) for Ukrainian text.
    text = re.sub(r'[^a-zA-Zа-яА-ЯІіЇїЄє0-9\s.,!?;:]', '', text)
    text = text.strip()

    sentences = sent_tokenize(text)

    current_sentence_index = 0
    while current_sentence_index < len(sentences):
        current_chunk_sentences = []
        current_chunk_length = 0

        # Add sentences from the end of the previous chunk for overlap
        if len(chunks) > 0:
            last_chunk_sentences = sent_tokenize(chunks[-1])
            temp_overlap_chars = 0
            overlap_sentences_for_this_chunk = []

            # Iterate backwards in the previous chunk's sentences to find enough for overlap
            for i in range(len(last_chunk_sentences) - 1, -1, -1):
                sentence = last_chunk_sentences[i]
                # Add 1 for the space that will be between sentences when joined
                if temp_overlap_chars + len(sentence) + (1 if temp_overlap_chars > 0 else 0) <= overlap:
                    overlap_sentences_for_this_chunk.insert(0, sentence) # Add to front to maintain order
                    temp_overlap_chars += len(sentence) + (1 if temp_overlap_chars > 0 else 0)
                else:
                    break
            current_chunk_sentences.extend(overlap_sentences_for_this_chunk)
            current_chunk_length = len(" ".join(current_chunk_sentences)) if current_chunk_sentences else 0

        # Now add new sentences from the `sentences` list until chunk_size is met
        temp_sentence_idx = current_sentence_index
        while temp_sentence_idx < len(sentences):
            sentence = sentences[temp_sentence_idx]
            # Check if adding this sentence will exceed chunk_size
            # Add 1 for the space that will be between sentences when joined
            if current_chunk_length + len(sentence) + (1 if current_chunk_sentences else 0) <= chunk_size:
                current_chunk_sentences.append(sentence)
                current_chunk_length += len(sentence) + (1 if current_chunk_sentences else 0)
                temp_sentence_idx += 1
            else:
                break # Current chunk is full enough

        # Handle cases where a single sentence is larger than chunk_size, or if no sentences were added
        if not current_chunk_sentences and current_sentence_index < len(sentences):
            # If the current_chunk_sentences is empty, it means the very first sentence is too long or no sentences were processed yet
            # Take the current sentence, even if it's too long, as a single chunk
            current_chunk_sentences.append(sentences[current_sentence_index])
            temp_sentence_idx = current_sentence_index + 1 # Advance pointer

        if current_chunk_sentences:
            chunks.append(" ".join(current_chunk_sentences))

        current_sentence_index = temp_sentence_idx # Move to the point where the next chunk should start

    return chunks

In [ ]:
chunked_data = []

for index, row in df.iterrows():
    title = row['Title']
    full_text = row['Text']

    # Split the full text into chunks
    chunks = text_splitter(full_text)

    # For each chunk, create a new entry with title, chunk text, and embedding
    for chunk in chunks:
        chunk_embedding = embed_text(chunk)
        chunked_data.append({'Title': title, 'Text': chunk, 'Embeddings': chunk_embedding})

# Create a new DataFrame from the chunked data
df_chunks = pd.DataFrame(chunked_data)

display(df_chunks.head())

In [ ]:
df_chunks = df_chunks.reset_index(drop=True)

df_chunks["Embeddings"] = df_chunks["Embeddings"].apply(lambda x: np.asarray(x, dtype=np.float32))

EMB_MATRIX = np.vstack(df_chunks["Embeddings"].to_numpy())
EMB_MATRIX_N = EMB_MATRIX / (np.linalg.norm(EMB_MATRIX, axis=1, keepdims=True) + 1e-12)

In [ ]:
get_relevant_chunks("Скільки в мене на рік доступно вихідних?")

In [28]:
def rag_implement_chunked(query):
    # Retrieval of relevant chunks
    relevant_texts, source_titles = get_relevant_chunks(query, num_chunks=3)

    # Concatenate relevant texts for the prompt
    context = " ".join(relevant_texts)

    # AG - Model
    model = genai.GenerativeModel(MODEL_NAME)

    # Augment --> prompt engineering
    prompt = f'Answer this query:\n{query}. \n Only use this context to answer: \n{context}'

    response = call_with_retry(model.generate_content, prompt)

    # Sourcing (titles of documents from which chunks were taken)
    source_titles = df_chunks[df_chunks['Text'].isin(relevant_texts)]['Title'].unique().tolist()

    return response.text, "\n".join(sorted(set(source_titles)))

In [ ]:
rag_implement_chunked("Скільки в мене на рік доступно вихідних?")

## Extending the user query

In [27]:
def extend_query(original_query):
    model = genai.GenerativeModel(MODEL_NAME)
    prompt = f"""Given the query: '{original_query}', generate 2-3 alternative ways to phrase this question that could be used to find similar information.
    Return each variant on a new line and include the original query as one of the options.
    Do not include any commentary, introductory or concluding text, just the list of queries.
    The result must be in the language of the original query, no translations. If it`s in English, return variants in English, if in Ukrainian, return in Ukrainian, etc."""
    response = call_with_retry(model.generate_content, prompt)
    extended_queries = [q.strip() for q in response.text.split('\n') if q.strip()]
    if original_query not in extended_queries:
        extended_queries.insert(0, original_query) # Ensure original query is always included
    return extended_queries

In [ ]:
extend_query("Чи є курси німецької?")

In [26]:
def rag_implement_chunked_extended(query: str):
    extended_queries = extend_query(query)

    combined_context_chunks = []
    source_titles = []

    # get 1 top chunk per extended query
    for ext_query in extended_queries:
        texts, titles = get_relevant_chunks(ext_query, num_chunks=1)  # unpack
        combined_context_chunks.extend(texts)
        source_titles.extend(titles)

    # remove duplicate chunks while preserving order
    seen = set()
    unique_chunks = []
    for t in combined_context_chunks:
        if t not in seen:
            unique_chunks.append(t)
            seen.add(t)

    final_relevant_texts = unique_chunks[:3]
    context = " ".join(final_relevant_texts)

    model = genai.GenerativeModel(MODEL_NAME)
    prompt = f"Answer this query:\n{query}\nOnly use this context to answer:\n{context}"
    response = call_with_retry(model.generate_content, prompt)

    used_titles = df_chunks[df_chunks["Text"].isin(final_relevant_texts)]["Title"].unique().tolist()

    return response.text, "\n".join(sorted(set(used_titles)))

In [ ]:
rag_implement_chunked_extended("Чи є курси німецької?")

## Demo queries — quick text proof before launching the chat UI
Run these to get printed Q&A with cited source, useful for a screenshot or for pasting straight into the portfolio write-up.

In [ ]:
question_en = "How many vacation days do I get per year, and can I carry them over?"
answer, sources = rag_implement_chunked_extended(question_en)
print(f"Q: {question_en}\nA: {answer}\nSource(s): {sources}")

In [ ]:
question_ua = "Скільки днів мені потрібно бути в офісі щотижня при гібридному графіку?"
answer, sources = rag_implement_chunked_extended(question_ua)
print(f"Q: {question_ua}\nA: {answer}\nSource(s): {sources}")

In [ ]:
import gradio as gr

description = "Welcome to HR policies bureau. Here you can ask anything about onboarding process, medical insuranse, leave policies and benefits."
title = "HR Wiki 👾"
output1 = gr.Textbox(label="Answer")
output2 = gr.Textbox(label="Where it comes from?")
gr.Interface(fn=rag_implement_chunked,
             title=title,
             description=description,
             inputs=["text"],
             outputs=[output1,output2]).launch(debug=True)

## Slack demo — one-off bot for a portfolio screenshot

Temporary: runs only while this cell is executing, in this Colab session. Not a deployed bot — for capturing a real Q&A screenshot in Slack, then stop the cell (Runtime → Interrupt execution) and revoke the Slack app token afterwards.

**Before running, in Slack (api.slack.com/apps):**
1. Create New App → From scratch → pick your workspace
2. Settings → Socket Mode → turn on → generate an App-Level Token with scope `connections:write` (starts with `xapp-`)
3. OAuth & Permissions → Bot Token Scopes → add `chat:write`, `channels:history`, `im:history`, `im:read`, `im:write`
4. Event Subscriptions → Subscribe to bot events → add `message.channels` and `message.im`
5. Install App to Workspace → copy the Bot User OAuth Token (starts with `xoxb-`)
6. Create (or pick) one dedicated test channel and invite the bot: `/invite @YourBotName`
7. Get that channel's ID: right-click the channel name → View channel details → the ID is at the bottom of that panel (starts with `C`)

**In Colab Secrets (🔑), add three new secrets** (same way as `GOOGLE_API_KEY`, Notebook access ON):
- `SLACK_BOT_TOKEN` = the `xoxb-...` token
- `SLACK_APP_TOKEN` = the `xapp-...` token
- `SLACK_TEST_CHANNEL_ID` = the channel ID from step 7 (e.g. `C0123456789`)

The bot only answers inside that one channel — see the channel check in the code below. That way, if this cell is accidentally left running, it doesn't start answering HR questions in every channel or DM it happens to be invited to.

In [ ]:
!pip install slack_bolt slack_sdk -q

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
from google.colab import userdata

slack_bot_token = userdata.get('SLACK_BOT_TOKEN')
slack_app_token = userdata.get('SLACK_APP_TOKEN')
allowed_channel_id = userdata.get('SLACK_TEST_CHANNEL_ID')

if not allowed_channel_id:
    raise ValueError(
        "SLACK_TEST_CHANNEL_ID secret is not set. Add it (see markdown cell above) "
        "before starting the bot — this keeps it from answering in every channel it's invited to."
    )

slack_app = App(token=slack_bot_token)

@slack_app.event("message")
def handle_message(event, say):
    # ignore the bot's own messages and message edits/subtypes
    if event.get("bot_id") or event.get("subtype"):
        return

    # only answer in the one dedicated test channel, ignore every other
    # channel/DM the bot might be invited to (accidentally or otherwise)
    if event.get("channel") != allowed_channel_id:
        return

    question = event.get("text", "").strip()
    if not question:
        return

    try:
        answer, sources = rag_implement_chunked_extended(question)
        say(f"*Answer:* {answer}\n*Source:* {sources}")
    except Exception as e:
        # don't leave the person hanging on a transient Gemini error (503/timeout/etc.)
        say("Sorry, I hit an error answering that (the model may be temporarily "
            f"overloaded). Try again in a moment. ({type(e).__name__})")

print(f"Bot is listening in channel {allowed_channel_id} only. Go ask it a question there.")
print("Stop this cell (Runtime -> Interrupt execution) once you have your screenshot.")

handler = SocketModeHandler(slack_app, slack_app_token)
handler.start()

In [31]:
print(rag_implement('Скільки днів відпустки на рік?'))

('Згідно з контекстом, повні дні оплачуваної щорічної відпустки (Paid Time Off, PTO) становлять **24 календарні дні на рік**.', 'Leave and Vacation Policy')